server:
  port: 8080

spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
          - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
          filters:
            - StripPrefix=0

        - id: menu-service-1
          uri: lb://menu-service-1
          predicates:
            - Path=/menuitems/**
          filters:
            - StripPrefix=0

        - id: table-service
          uri: lb://table-service
          predicates:
            - Path=/tables/**
          filters:
            - StripPrefix=0

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
